package model

const (
	TaskTypeCodeAudit       = "code_audit"
	TaskTypePentest         = "pentest"
	TaskTypeInternalPentest = "internal_pentest"
	TaskTypeTerminalProof   = "terminal_proof"
	TaskTypeHybrid          = "hybrid"

	TaskStatusPending   = "pending"
	TaskStatusRunning   = "running"
	TaskStatusPaused    = "paused"
	TaskStatusCompleted = "completed"
	TaskStatusFailed    = "failed"
	TaskStatusCancelled = "cancelled"

	FindingStatusHypothesis           = "hypothesis"
	FindingStatusCandidate            = "candidate"
	FindingStatusCandidateIncomplete  = "candidate_incomplete"
	FindingStatusContractIncomplete   = "contract_incomplete"
	FindingStatusDynamicallyValidated = "dynamically_validated"
	FindingStatusHumanConfirmed       = "human_confirmed"
	FindingStatusFalsePositive        = "false_positive"
	FindingStatusAcceptedRisk         = "accepted_risk"
	FindingStatusFixed                = "fixed"
	FindingStatusRetested             = "retested"

	ValidationNotAttempted         = "not_attempted"
	ValidationToolObserved         = "tool_observed"
	ValidationContractIncomplete   = "contract_incomplete"
	ValidationDynamicallyValidated = "dynamically_validated"
	ValidationHumanConfirmed       = "human_confirmed"
	ContractStatusNotChecked       = "not_checked"
	ContractStatusPassed           = "passed"
	ContractStatusIncomplete       = "incomplete"
	ContractStatusFailed           = "failed"
	HumanReviewPending             = "pending"
	HumanReviewConfirmed           = "confirmed"
	HumanReviewFalsePositive       = "false_positive"
	HumanReviewAcceptedRisk        = "accepted_risk"
	IntentStatusPending            = "pending"
	IntentStatusClaimed            = "claimed"
	IntentStatusRunning            = "running"
	IntentStatusCompleted          = "completed"
	IntentStatusFailed             = "failed"
	IntentStatusCancelled          = "cancelled"
	IntentStatusSuppressed         = "suppressed"
	IntentStatusArchived           = "archived"
	ToolRunStatusPending           = "pending"
	ToolRunStatusRunning           = "running"
	ToolRunStatusSuccess           = "success"
	ToolRunStatusFailed            = "failed"
	ToolRunStatusTimeout           = "timeout"
	ToolRunStatusBlocked           = "blocked"
	BlackboardNodeStatusActive     = "active"
	BlackboardNodeStatusMerged     = "merged"
	BlackboardNodeStatusArchived   = "archived"
	BlackboardNodeStatusSuppressed = "suppressed"
	ReportStatusDraft              = "draft"
	ReportStatusReady              = "ready"
	ReportStatusFailed             = "failed"

	ModelPurposeBrain  = "brain"
	ModelPurposeWorker = "worker"
	ModelPurposeBoth   = "both"
)
